
class: split-50  

.column.bg-main1[.content.vmiddle[

# View the median .pink[qualities] of houses from different categories of .orange[neighborhood]

 

]]

.column.bg-main5[.content.vmiddle.center[
<center>

```{r, echo = F}
library(fmsb)
no_na = readRDS("data/no_na_but_saleprice.rds")
```

```{r, echo = F, out.width= "90%"}

no_na %>% 
  select("BsmtQual", "FireplaceQu", "GarageQual", "KitchenQual",
         "ExterQual", "Neighborhood") -> qual_data

colnames(qual_data) = c("BsmtQual", "FireplaceQual", "GarageQual", "KitchenQual",
                        "ExterQual", "Neighborhood")

qual_data$NeighRich[qual_data$Neighborhood %in% c('StoneBr', 'NridgHt', 'NoRidge')] <- 2
qual_data$NeighRich[!qual_data$Neighborhood %in% c('MeadowV', 'IDOTRR', 'BrDale', 'StoneBr', 'NridgHt', 'NoRidge')] <- 1
qual_data$NeighRich[qual_data$Neighborhood %in% c('MeadowV', 'IDOTRR', 'BrDale')] <- 0

median_qual_data = qual_data %>%
  group_by(NeighRich) %>%
  summarise_at(vars(ends_with("Qual")), median)
median_qual_data <- rbind(rep(5,5) , rep(0,5) , median_qual_data)



colors_border=c( rgb(0.2,0.5,0.5,0.9), rgb(0.8,0.2,0.5,0.9) , rgb(0.7,0.5,0.1,0.9) )
colors_in=c( rgb(0.2,0.5,0.5,0.5), rgb(0.8,0.2,0.5,0.5) , rgb(0.7,0.5,0.1,0.5) )

radarchart(median_qual_data[2:6], axistype=1 , 
           #custom polygon
           pcol=colors_border , pfcol=colors_in, plwd=4 , plty=1,
           #custom the grid
           cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,5,1), cglwd=0.8,
           #custom labels
           vlcex=1, 
           cex.lab=1.5)
legend(x=0.7, y=1.3, legend = c("economical", "middle", "wealthy"), bty = "n", 
       pch=20 , col=colors_in , text.col = "grey", cex=1.2, pt.cex=3)
```


]]
